# the vector space for the words will eventually change in the space sd they get close to the ones which has similar meaing 


In [1]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#read the words
words = open('../names.txt', 'r').read().splitlines()

In [3]:
len(words)

32033

In [4]:
#get all non-repeating charcs in once
# build the vocal of chars and mappings to/from integers
chars = sorted(list(set(''.join(words))))
stoi1 = {s:i+1 for i,s in enumerate(chars)}
stoi = {s:i for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}

In [5]:
print(itos)

{0: '.', 1: 'b', 2: 'c', 3: 'd', 4: 'e', 5: 'f', 6: 'g', 7: 'h', 8: 'i', 9: 'j', 10: 'k', 11: 'l', 12: 'm', 13: 'n', 14: 'o', 15: 'p', 16: 'q', 17: 'r', 18: 's', 19: 't', 20: 'u', 21: 'v', 22: 'w', 23: 'x', 24: 'y', 25: 'z'}


In [14]:
#re building the dataset
block_size = 3 #context_length; how many charactors do we take to predict the next one
X, Y = [], []
for w in words[:5]:
    print(w)
    context = [0] * block_size
    for ch in w + '.':
        ix = stoi[ch]
        X.append(context)
        Y.append(ix)
        print(''.join(itos[i] for i in context), '----->' ,itos[ix])
        context = context[1:] + [ix]
X = torch.tensor(X)
Y = torch.tensor(Y)

emma
... -----> e
..e -----> m
.em -----> m
emm -----> .
mm. -----> .
olivia
... -----> o
..o -----> l
.ol -----> i
oli -----> v
liv -----> i
ivi -----> .
vi. -----> .
ava
... -----> .
... -----> v
..v -----> .
.v. -----> .
isabella
... -----> i
..i -----> s
.is -----> .
is. -----> b
s.b -----> e
.be -----> l
bel -----> l
ell -----> .
ll. -----> .
sophia
... -----> s
..s -----> o
.so -----> p
sop -----> h
oph -----> i
phi -----> .
hi. -----> .


In [7]:
X.shape, X.dtype, Y.shape, Y.shape

(torch.Size([32, 3]), torch.int64, torch.Size([32]), torch.Size([32]))

In [8]:
X

tensor([[ 0,  0,  0],
        [ 0,  0,  4],
        [ 0,  4, 12],
        [ 4, 12, 12],
        [12, 12,  0],
        [ 0,  0,  0],
        [ 0,  0, 14],
        [ 0, 14, 11],
        [14, 11,  8],
        [11,  8, 21],
        [ 8, 21,  8],
        [21,  8,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0, 21],
        [ 0, 21,  0],
        [ 0,  0,  0],
        [ 0,  0,  8],
        [ 0,  8, 18],
        [ 8, 18,  0],
        [18,  0,  1],
        [ 0,  1,  4],
        [ 1,  4, 11],
        [ 4, 11, 11],
        [11, 11,  0],
        [ 0,  0,  0],
        [ 0,  0, 18],
        [ 0, 18, 14],
        [18, 14, 15],
        [14, 15,  7],
        [15,  7,  8],
        [ 7,  8,  0]])

In [34]:
Y

tensor([ 4, 12, 12,  0,  0, 14, 11,  8, 21,  8,  0,  0,  0, 21,  0,  0,  8, 18,
         0,  1,  4, 11, 11,  0,  0, 18, 14, 15,  7,  8,  0,  0])

In [21]:
#lookup table
C = torch.randn((27,2))

In [22]:
C

tensor([[ 0.7333,  0.4348],
        [-0.0435,  0.3219],
        [ 0.3716,  0.7941],
        [ 2.3148, -0.1013],
        [-1.1035, -0.5392],
        [ 1.4572, -1.8976],
        [ 1.4104,  1.1924],
        [ 1.5057, -0.3508],
        [ 0.6329,  0.1063],
        [ 1.6690, -0.0285],
        [-0.5831, -1.6122],
        [-1.3108, -0.0958],
        [-0.6510, -0.3388],
        [-0.0956, -1.9286],
        [ 1.5426,  0.6763],
        [-0.4134,  0.0103],
        [-0.2853, -2.3369],
        [-0.0933, -1.4080],
        [-0.3136,  0.0463],
        [ 1.0572, -1.1418],
        [ 0.6735, -0.3117],
        [-0.8310, -0.2337],
        [-1.5864,  0.0429],
        [ 0.5717, -0.3271],
        [ 1.5134, -0.2060],
        [ 0.3820, -0.0551],
        [-0.6686,  0.4358]])